Updated .sln file to VS 2013 format.
* Fixed "error C1041: cannot open program database" by changing intermediate directory.
* Removed solution reference to missing project testsnolib
* Added project reference to resolve build order issues.